"""empty message

Revision ID: 1ba44f28bb2c
Revises: 6d4e1d976b48
Create Date: 2026-10-07 23:53:05.101815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba44f28bb2c'
down_revision = '6d4e1d976b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('authProvider',
               existing_type=sa.INTEGER(),
               nullable=1)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('authProvider',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
