"""empty message

Revision ID: 4915bf227c2a
Revises: 
Create Date: 2026-09-27 12:34:47.414485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4915bf227c2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('authProvider',
               existing_type=sa.INTEGER(),
               nullable=1)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('authProvider',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
