"""empty message

Revision ID: 641e5f1f868d
Revises: 48066c55da1d
Create Date: 2026-10-07 23:36:00.300643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641e5f1f868d'
down_revision = '48066c55da1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('authProvider',
               existing_type=sa.INTEGER(),
               nullable=1)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('authProvider',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
