"""empty message

Revision ID: 6d4e1d976b48
Revises: 641e5f1f868d
Create Date: 2026-10-07 23:43:45.854816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4e1d976b48'
down_revision = '641e5f1f868d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('authProvider',
               existing_type=sa.INTEGER(),
               nullable=1)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('authProvider',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
